version: "3.3"

services: 
    frontend: 
        container_name: frontend
        image: adityaudi/frontend-coffeeshop:developement
        ports: 
            - "80:80"
        networks:
            - networkid
        environment:
            - VUE_APP_URL=http://184.72.88.25/product
            - VUE_APP_URL_HISTORY=http://184.72.88.25/history
            - VUE_APP_URL_USERS=http://184.72.88.25/users
            - VUE_APP_URL_AUTH=http://184.72.88.25/auth

    nodejs:
        container_name: nodejs
        image: adityaudi/backend-coffeeshop:developement
        ports:
            - "9090:4040"
        networks:
            - networkid
        environment:
            - PORT=9090

            - DB_NAME=coffeeshop
            - DB_USER=adityaudi
            - DB_PASS=22
            - DB_HOST=172.31.81.38

            - SECRET_KEY=adityaudi

            - REDIS_PORT=6379
            - REDIS_HOST=172.31.81.38

networks:
    networkid:
