version: "3.3"

services: 
    frontend: 
        container_name: frontend
        image: adityaudi/frontend-coffeeshop:developement
        ports: 
            - "80:80"
            - "443:443"
        networks:
            - networkid
        environment:
            - VUE_APP_URL=http://3.92.189.20/product
            - VUE_APP_URL_HISTORY=http://3.92.189.20/history
            - VUE_APP_URL_USERS=http://3.92.189.20/users
            - VUE_APP_URL_AUTH=http://3.92.189.20/auth

    nodejs:
        container_name: nodejs
        image: adityaudi/backend-coffeeshop:developement
        ports:
            - "9090:4040"
        networks:
            - networkid
        environment:
            - PORT=9090

            - DB_NAME=coffeeshop
            - DB_USER=adityaudi
            - DB_PASS=22
            - DB_HOST=3.92.189.20

            - SECRET_KEY=adityaudi

            - REDIS_PORT=6379
            - REDIS_HOST=3.92.189.20

networks:
    networkid:
